import { julesApi } from '../julesApi';
import { Type, FunctionDeclaration } from '@google/genai';

export const julesTools = [
  {
    type: 'function' as const,
    function: {
      name: 'listSessions',
      description: 'List recent Jules API sessions',
      parameters: {
        type: 'object',
        properties: {
          pageSize: { type: 'number', description: 'Number of sessions to return' },
        },
      },
    },
  },
  {
    type: 'function' as const,
    function: {
      name: 'createSession',
      description: 'Create a new Jules API session to run a coding task or bug fix',
      parameters: {
        type: 'object',
        properties: {
          prompt: { type: 'string', description: 'The prompt or task for Jules to execute' },
          title: { type: 'string', description: 'Optional title for the session' },
        },
        required: ['prompt'],
      },
    },
  },
  {
    type: 'function' as const,
    function: {
      name: 'sendMessage',
      description: 'Send a message to an active Jules session to reply to questions or give instructions',
      parameters: {
        type: 'object',
        properties: {
          sessionId: { type: 'string', description: 'The ID of the session' },
          prompt: { type: 'string', description: 'The message to send' },
        },
        required: ['sessionId', 'prompt'],
      },
    },
  },
  {
    type: 'function' as const,
    function: {
      name: 'approvePlan',
      description: 'Approve the plan generated by Jules for a session, so it can start executing',
      parameters: {
        type: 'object',
        properties: {
          sessionId: { type: 'string', description: 'The ID of the session' },
        },
        required: ['sessionId'],
      },
    },
  },
  {
    type: 'function' as const,
    function: {
      name: 'listActivities',
      description: 'List activities (messages, plan generation, code changes) for a specific session',
      parameters: {
        type: 'object',
        properties: {
          sessionId: { type: 'string', description: 'The ID of the session' },
          pageSize: { type: 'number', description: 'Number of activities to return' },
        },
        required: ['sessionId'],
      },
    },
  },
  {
    type: 'function' as const,
    function: {
      name: 'deleteSession',
      description: 'Delete a specific session',
      parameters: {
        type: 'object',
        properties: {
          sessionId: { type: 'string', description: 'The ID of the session' },
        },
        required: ['sessionId'],
      },
    },
  },
];

export const geminiJulesTools = [
  {
    name: 'listSessions',
    description: 'List recent Jules API sessions',
    parameters: {
      type: Type.OBJECT,
      properties: {
        pageSize: { type: Type.NUMBER, description: 'Number of sessions to return' },
      },
    },
  },
  {
    name: 'createSession',
    description: 'Create a new Jules API session to run a coding task or bug fix',
    parameters: {
      type: Type.OBJECT,
      properties: {
        prompt: { type: Type.STRING, description: 'The prompt or task for Jules to execute' },
        title: { type: Type.STRING, description: 'Optional title for the session' },
      },
      required: ['prompt'],
    },
  },
  {
    name: 'sendMessage',
    description: 'Send a message to an active Jules session to reply to questions or give instructions',
    parameters: {
      type: Type.OBJECT,
      properties: {
        sessionId: { type: Type.STRING, description: 'The ID of the session' },
        prompt: { type: Type.STRING, description: 'The message to send' },
      },
      required: ['sessionId', 'prompt'],
    },
  },
  {
    name: 'approvePlan',
    description: 'Approve the plan generated by Jules for a session, so it can start executing',
    parameters: {
      type: Type.OBJECT,
      properties: {
        sessionId: { type: Type.STRING, description: 'The ID of the session' },
      },
      required: ['sessionId'],
    },
  },
  {
    name: 'listActivities',
    description: 'List activities (messages, plan generation, code changes) for a specific session',
    parameters: {
      type: Type.OBJECT,
      properties: {
        sessionId: { type: Type.STRING, description: 'The ID of the session' },
        pageSize: { type: Type.NUMBER, description: 'Number of activities to return' },
      },
      required: ['sessionId'],
    },
  },
  {
    name: 'deleteSession',
    description: 'Delete a specific session',
    parameters: {
      type: Type.OBJECT,
      properties: {
        sessionId: { type: Type.STRING, description: 'The ID of the session' },
      },
      required: ['sessionId'],
    },
  },
] as FunctionDeclaration[];

export interface ParsedInlineToolCall {
  name: string;
  args: any;
  rawText: string;
}

export function parseInlineToolCalls(text: string): ParsedInlineToolCall[] {
  const results: ParsedInlineToolCall[] = [];
  // Regex to match <tool_call>FunctionName key=value key="value"...</arg_value>
  // Or just <tool_call>...</tool_call>
  // Note: removing 's' flag to fix TypeScript targeting ES2015. We can use [\s\S]* instead of .*? with s flag
  const toolCallRegex = /<tool_call>\s*([a-zA-Z0-9_]+)\s*([\s\S]*?)(?:<\/arg_value>|<\/tool_call>|>|$)/g;

  let match;
  while ((match = toolCallRegex.exec(text)) !== null) {
    const rawText = match[0];
    let name = match[1];
    const argsString = match[2];

    // Map hallucinated names to correct ones
    if (name === 'getActivities') name = 'listActivities';
    if (name === 'getSessions') name = 'listSessions';

    const args: any = {};
    const argRegex = /([a-zA-Z0-9_]+)=("([^"]*)"|'([^']*)'|(\S+))/g;
    let argMatch;
    while ((argMatch = argRegex.exec(argsString)) !== null) {
      const key = argMatch[1];
      let value = argMatch[3] !== undefined ? argMatch[3] : (argMatch[4] !== undefined ? argMatch[4] : argMatch[5]);

      if (value === undefined) value = "";

      // Convert small number strings to actual numbers, avoid precision loss on IDs
      if (/^[0-9]+$/.test(value) && value.length < 10) {
        args[key] = parseInt(value, 10);
      } else if (value === 'true') {
        args[key] = true;
      } else if (value === 'false') {
        args[key] = false;
      } else {
        args[key] = value;
      }
    }

    results.push({ name, args, rawText });
  }
  return results;
}

export async function executeJulesTool(
  julesApiKey: string,
  name: string,
  args: any,
): Promise<any> {
  if (!julesApiKey) {
    throw new Error("Missing Jules API Key");
  }

  switch (name) {
    case 'listSessions':
      return await julesApi.listSessions(julesApiKey, args.pageSize || 10);
    case 'createSession':
      return await julesApi.createSession(julesApiKey, {
        prompt: args.prompt,
        title: args.title,
      });
    case 'sendMessage':
      await julesApi.sendMessage(julesApiKey, args.sessionId, args.prompt);
      return { status: 'success' };
    case 'approvePlan':
      await julesApi.approvePlan(julesApiKey, args.sessionId);
      return { status: 'success' };
    case 'listActivities':
      return await julesApi.listActivities(julesApiKey, args.sessionId, args.pageSize || 10);
    case 'deleteSession':
      await julesApi.deleteSession(julesApiKey, args.sessionId);
      return { status: 'success' };
    default:
      throw new Error(`Unknown tool: ${name}`);
  }
}
